// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import GeneralMapController from "./general_map_controller.js"
application.register("general-map", GeneralMapController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import MapController from "./map_controller.js"
application.register("map", MapController)

import NavbarController from "./navbar_controller.js"
application.register("navbar", NavbarController)

import RequestController from "./request_controller.js"
application.register("request", RequestController)

import SlideController from "./slide_controller.js"
application.register("slide", SlideController)

import TabsController from "./tabs_controller.js"
application.register("tabs", TabsController)
